# Generated by Django 2.2.5 on 2020-01-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='password', max_length=50, verbose_name='password')),
                ('tch_name', models.CharField(max_length=10, null=True, verbose_name='teacher name')),
                ('tch_mobile', models.CharField(max_length=15, unique=True, verbose_name='mobile')),
                ('tch_register_time', models.DateTimeField(default='2020-01-01 00:00:00', null=True, verbose_name='register time')),
                ('tch_last_login_time', models.DateTimeField(default='2020-01-01 00:00:00', null=True, verbose_name='last log in time')),
                ('tch_last_login_ip', models.CharField(max_length=30, null=True, verbose_name='last log in ip')),
                ('tch_profile', models.CharField(max_length=200, null=True)),
                ('tch_univ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.NepUniversity')),
            ],
            options={
                'db_table': 'nep_teacher',
                'managed': True,
            },
        ),
    ]
