# Generated by Django 2.2.5 on 2020-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nepstudent',
            old_name='stu_cour_info',
            new_name='stu_recommend_cour_info',
        ),
        migrations.AddField(
            model_name='nepstudent',
            name='stu_graduate_date',
            field=models.DateField(max_length=15, null=True),
        ),
    ]
