# Generated by Django 2.2.5 on 2020-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NepCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour_name', models.CharField(max_length=45)),
                ('cour_type', models.CharField(choices=[(5, '外语'), (1, '化学'), (3, '地理'), (6, '政治'), (8, '医学'), (9, '法学'), (4, '信息技术'), (0, '数学'), (7, '历史'), (2, '物理')], default='unknow', max_length=10)),
                ('cour_start', models.DateTimeField(null=True)),
                ('cour_end', models.DateTimeField(null=True)),
                ('cour_dir', models.CharField(max_length=45, null=True)),
                ('cour_avilable', models.BooleanField(default=True)),
                ('cour_description', models.TextField(null=True)),
                ('cour_create_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'nep_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NepUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(default='unknow', max_length=30, verbose_name='university name')),
                ('univ_city', models.CharField(default='unknow', max_length=10, verbose_name='university city')),
                ('univ_description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'db_table': 'nep_university',
                'managed': True,
            },
        ),
    ]
