# Generated by Django 2.2.5 on 2020-01-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepcourse',
            name='cour_create_tch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.NepTeacher'),
        ),
        migrations.AddField(
            model_name='nepcourse',
            name='cour_univ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.NepUniversity'),
        ),
    ]
