# Generated by Django 2.2.5 on 2020-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200102_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepcourse',
            name='cour_image',
            field=models.ImageField(height_field=92, null=True, upload_to='', width_field=182),
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('3', '地理'), ('9', '法学'), ('4', '信息技术'), ('8', '医学'), ('6', '政治'), ('2', '物理'), ('0', '数学'), ('7', '历史'), ('5', '外语'), ('1', '化学')], default='unknow', max_length=10),
        ),
    ]
