# Generated by Django 2.2.5 on 2020-02-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('index', '0003_auto_20200106_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('5', '外语'), ('1', '化学'), ('10', '经济学'), ('8', '医学'), ('9', '法学'), ('6', '政治'), ('2', '物理'), ('7', '历史'), ('4', '信息技术'), ('0', '数学'), ('3', '地理')], default='unknow', max_length=10),
        ),
        migrations.CreateModel(
            name='NepSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect_name', models.CharField(max_length=50)),
                ('sect_text', models.CharField(max_length=500, null=True)),
                ('sect_media', models.FileField(null=True, upload_to='')),
                ('sect_number', models.IntegerField(default=0)),
                ('sect_create_time', models.DateTimeField(null=True)),
                ('sect_cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NepCourse')),
                ('sect_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.NepTeacher')),
            ],
        ),
    ]
