# Generated by Django 2.2.5 on 2020-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200226_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nepsection',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('5', '外语'), ('9', '法学'), ('2', '物理'), ('1', '化学'), ('8', '医学'), ('6', '政治'), ('7', '历史'), ('0', '数学'), ('10', '经济学'), ('4', '信息技术'), ('3', '地理')], default='unknow', max_length=10),
        ),
        migrations.AlterModelTable(
            name='nepsection',
            table='nep_section',
        ),
    ]
