# Generated by Django 2.2.5 on 2020-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200226_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nepsection',
            name='sect_number',
        ),
        migrations.AddField(
            model_name='nepsection',
            name='sect_tag',
            field=models.CharField(default='section_1-1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('4', '信息技术'), ('2', '物理'), ('7', '历史'), ('10', '经济学'), ('5', '外语'), ('0', '数学'), ('3', '地理'), ('1', '化学'), ('6', '政治'), ('9', '法学'), ('8', '医学')], default='unknow', max_length=10),
        ),
        migrations.AlterField(
            model_name='nepsection',
            name='sect_media',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
