# Generated by Django 2.2.5 on 2020-03-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('index', '0006_auto_20200228_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('9', '法学'), ('7', '历史'), ('0', '数学'), ('10', '经济学'), ('5', '外语'), ('4', '信息技术'), ('6', '政治'), ('3', '地理'), ('1', '化学'), ('8', '医学'), ('2', '物理')], default='unknow', max_length=10),
        ),
        migrations.CreateModel(
            name='NepLearnStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('last_time', models.DateTimeField(null=True)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NepCourse')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.NepStudent')),
            ],
            options={
                'db_table': 'nep_learn_status',
                'managed': True,
            },
        ),
    ]
