# Generated by Django 2.2.5 on 2020-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200307_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neplearnstatus',
            old_name='id_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='neplearnstatus',
            old_name='id_student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('0', '数学'), ('10', '经济学'), ('3', '地理'), ('6', '政治'), ('7', '历史'), ('8', '医学'), ('4', '信息技术'), ('5', '外语'), ('9', '法学'), ('1', '化学'), ('2', '物理')], default='unknow', max_length=10),
        ),
    ]
