# Generated by Django 2.2.5 on 2020-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200311_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('3', '地理'), ('4', '信息技术'), ('1', '化学'), ('2', '物理'), ('0', '数学'), ('6', '政治'), ('7', '历史'), ('10', '经济学'), ('5', '外语'), ('9', '法学'), ('8', '医学')], default='unknow', max_length=10),
        ),
        migrations.AlterField(
            model_name='nepsection',
            name='sect_media',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
