# Generated by Django 2.2.5 on 2020-03-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200314_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('8', '医学'), ('5', '外语'), ('0', '数学'), ('6', '政治'), ('2', '物理'), ('9', '法学'), ('3', '地理'), ('7', '历史'), ('10', '经济学'), ('4', '信息技术'), ('1', '化学')], default='unknow', max_length=10),
        ),
        migrations.AlterField(
            model_name='nepsection',
            name='sect_tag',
            field=models.CharField(default='1-1', max_length=20),
        ),
    ]
