# Generated by Django 2.2.5 on 2020-03-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('index', '0010_auto_20200314_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('2', '物理'), ('4', '信息技术'), ('7', '历史'), ('1', '化学'), ('9', '法学'), ('0', '数学'), ('10', '经济学'), ('6', '政治'), ('5', '外语'), ('8', '医学'), ('3', '地理')], default='unknow', max_length=10),
        ),
        migrations.CreateModel(
            name='NepSectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('last_time', models.DateTimeField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('view_time', models.TimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NepCourse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NepSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.NepStudent')),
            ],
            options={
                'db_table': 'nep_section_status',
                'managed': True,
            },
        ),
    ]
