# Generated by Django 2.2.5 on 2020-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200323_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('1', '经济学'), ('4', '文学'), ('11', '艺术学'), ('13', '其他'), ('9', '医学'), ('10', '管理学'), ('2', '法学'), ('3', '教育学'), ('6', '理学'), ('0', '哲学'), ('5', '历史学'), ('8', '农学'), ('7', '工学'), ('12', '军事学')], default='unknow', max_length=10),
        ),
    ]
