# Generated by Django 2.2.5 on 2020-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200422_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='neplearnstatus',
            name='learn_frequency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nepcourse',
            name='cour_type',
            field=models.CharField(choices=[('3', '教育学'), ('5', '历史学'), ('2', '法学'), ('13', '其他'), ('12', '军事学'), ('11', '艺术学'), ('1', '经济学'), ('0', '哲学'), ('4', '文学'), ('9', '医学'), ('10', '管理学'), ('8', '农学'), ('7', '工学'), ('6', '理学')], default='unknow', max_length=10),
        ),
    ]
